version: "3"
services:
  oracle11g:
    image: jaspeen/oracle-xe-11g
    container_name: oracle11g
    ports:
      - 1521:1521
      - 8080:8080

  douzon-docker:
    image: lkw99/douzon-docker
    build: .
    ports:
      - 8081:8081