server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: douzon
    password: 1234

messages:
  basename: messages

management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosa.restaurants.DO
