server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@kapplescm_high?TNS_ADMIN=C:/Users/KOSA/Downloads/Wallet_kapplescm
    username: dev
    password: Douzone12345

messages:
  basename: messages

management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosa.Kapple.domain, com.kosa.Kapple.vo
  configuration:
    jdbc-type-for-null: varchar
