server:
  port: 5000
#aws 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@DB이름:1521:ORCL
    username: sysdba
    password: kosa1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosa.douzondocker.VO
